%% 飞机在风中飞行往返时间
clc;clear;close all;                     % 清除变量
u =linspace(0,0.9,100);                  % 空气速率与飞机速率之比的向量
theta = 0:30:90;                         % 角度向量
th = theta*pi/180;                       % 化为弧度
[U,TH] = meshgrid(u,th);                 % 速率和角度矩阵

T1=1/2./(sqrt(1-(U.*sin(TH)).^2)+U.*cos(TH));
T2=1/2./(sqrt(1-(U.*sin(TH)).^2)-U.*cos(TH));
T=sqrt(1-(U.*sin(TH)).^2)./(1-U.^2);     
%% 
fs=16;                                 % 字体大小

figure                                                               
set(gcf,'Color','w','InvertHardcopy','off')% 图窗背景纯白
set(gcf,'DefaultTextColor','k', ...
    'DefaultTextFontName','Times New Roman',...
    'DefaultTextFontSize',fs)             % 文字黑色 Times New Roman 16号
set(gcf,'DefaultAxesColor','w','DefaultAxesXColor','k', ...
    'DefaultAxesYColor','k',...
    'DefaultAxesZColor','k','DefaultAxesBox','on') % 坐标轴白底黑字加边框
set(gcf,'DefaultAxesFontName','Times New Roman', ...
    'DefaultAxesFontSize',fs)      % 坐标轴字体

plot(u,T(1,:),'o-', ...
    u,T(2,:),'d-', ...
    u,T(3,:),'s-', ...
    u,T(4,:),'v-','LineWidth',2,"Color","r", ...
    'MarkerIndices',1:5:length(u))  % 画往返时间曲线族
hold on                              
plot(u,T1(1,:),'o-', ...
    u,T1(2,:),'d-', ...
    u,T1(3,:),'s-', ...
    u,T1(4,:),'v-','LineWidth',2,"Color","g", ...
    'MarkerIndices',1:5:length(u))% 画A到B的时间曲线族
plot(u,T2(1,:),'o-', ...
    u,T2(2,:),'d-', ...
    u,T2(3,:),'s-', ...
    u,T2(4,:),'v-','LineWidth',2,"Color","b", ...
    'MarkerIndices',1:5:length(u)) % 画B到A的时间曲线族
grid on                           

title('飞机往返的时间与风速的关系', ...
    'FontSize',fs,"FontName","宋体")         % 标题
xlabel('$\it w/v$', ...
    'FontSize',fs,'Interpreter',"LaTex")     % 标记横坐标
ylabel('$t/t\rm_0$', ...
    'FontSize',fs,'Interpreter',"LaTex")     % 标记纵坐标
n=length(theta);                             % 角度个数
legend([repmat('$\theta\rm =$',n,1), ...
    num2str(theta'),repmat('$^{\circ}$',n,1)], ...
    "interpreter","latex",...
    "Color","w","box","off","Location","best", ...
    "textColor","k")                         % 图例
text(0,1.2,'$t_0 = 2l/v$', ...
    'FontSize',fs,"Interpreter","latex")     % 标记时间单位

figure(fs)
set(gcf,'Color','w','InvertHardcopy','off')% 图窗背景纯白
set(gcf,'DefaultTextColor','k', ...
    'DefaultTextFontName','Times New Roman',...
    'DefaultTextFontSize',fs)             % 文字黑色 Times New Roman 16号
set(gcf,'DefaultAxesColor','w','DefaultAxesXColor','k', ...
    'DefaultAxesYColor','k',...
    'DefaultAxesZColor','k','DefaultAxesBox','on') % 坐标轴白底黑字加边框
set(gcf,'DefaultAxesFontName','Times New Roman', ...
    'DefaultAxesFontSize',fs)      % 坐标轴字体
plot(u,T2(1,:)-T1(1,:),'o-', ...
    u,T2(2,:)-T1(2,:),'d-', ...
    u,T2(3,:)-T1(3,:),'s-', ...
    u,T2(4,:)-T1(4,:),'v-','LineWidth',2, ...
    'MarkerIndices',1:5:length(u))% 画A到B的时间曲线族
xlabel('$\it w/v$', ...
    'FontSize',fs,'Interpreter',"LaTex")     % 标记横坐标
ylabel('$(t_2-t_1)/t\rm_0$', ...
    'FontSize',fs,'Interpreter',"LaTex")     % 标记纵坐标
n=length(theta);                             % 角度个数
legend([repmat('$\theta\rm =$',n,1), ...
    num2str(theta'),repmat('$^{\circ}$',n,1)], ...
    "interpreter","latex",...
    "Color","w","box","off","Location","best", ...
    "textColor","k")                         % 图例
text(0,1.2,'$t_0 = 2l/v$', ...
    'FontSize',fs,"Interpreter","latex")     % 标记时间单位